//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarNoteWebApi.EntitiyDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StarNoteEntity : DbContext
    {
        public StarNoteEntity()
            : base("name=StarNoteEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<partial_analysis> partial_analysis { get; set; }
        public DbSet<partial_saleschart> partial_saleschart { get; set; }
        public DbSet<partial_salesman> partial_salesman { get; set; }
        public DbSet<partial_salespie> partial_salespie { get; set; }
        public DbSet<tbl_case> tbl_case { get; set; }
        public DbSet<tbl_company> tbl_company { get; set; }
        public DbSet<tbl_costumer> tbl_costumer { get; set; }
        public DbSet<tbl_kdvsource> tbl_kdvsource { get; set; }
        public DbSet<tbl_lisance> tbl_lisance { get; set; }
        public DbSet<tbl_note> tbl_note { get; set; }
        public DbSet<tbl_paymenttype> tbl_paymenttype { get; set; }
        public DbSet<tbl_product> tbl_product { get; set; }
        public DbSet<tbl_remember> tbl_remember { get; set; }
        public DbSet<tbl_rememberstatus> tbl_rememberstatus { get; set; }
        public DbSet<tbl_remembertype> tbl_remembertype { get; set; }
        public DbSet<tbl_salesman> tbl_salesman { get; set; }
        public DbSet<tbl_stok> tbl_stok { get; set; }
        public DbSet<tbl_type> tbl_type { get; set; }
        public DbSet<tbl_typedetail> tbl_typedetail { get; set; }
        public DbSet<tbl_unit> tbl_unit { get; set; }
        public DbSet<tbl_users> tbl_users { get; set; }
        public DbSet<tbl_processtype> tbl_processtype { get; set; }
        public DbSet<tbl_joborder> tbl_joborder { get; set; }
        public DbSet<tbl_filemanagement> tbl_filemanagement { get; set; }
        public DbSet<tbl_customerorder> tbl_customerorder { get; set; }
    }
}
