//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarNoteWebApi.EntitiyDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_remember
    {
        public int Id { get; set; }
        public int Upperid { get; set; }
        public string Record { get; set; }
        public string Recorddetail { get; set; }
        public string Remindingtype { get; set; }
        public string Remindingmsg { get; set; }
        public string Remindingstatus { get; set; }
    }
}
