//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarNoteWebApi.EntitiyDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_joborder
    {
        public int Id { get; set; }
        public Nullable<int> Upperid { get; set; }
        public string JobOrderNo { get; set; }
        public string Product { get; set; }
        public string Product2 { get; set; }
        public string Producttype { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Amounttype { get; set; }
        public Nullable<double> Price { get; set; }
        public string State { get; set; }
        public string Info { get; set; }
        public Nullable<double> Suggestedprice { get; set; }
        public Nullable<double> Countedprice { get; set; }
        public Nullable<int> Numberofline { get; set; }
        public Nullable<int> Numberofword { get; set; }
        public Nullable<int> Numberofchar { get; set; }
        public Nullable<int> Countedamount { get; set; }
    }
}
