//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarNoteWebApi.EntitiyDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_lisance
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string PRODUCTID { get; set; }
        public string END_DATE { get; set; }
        public string STATUS { get; set; }
    }
}
