//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarNoteWebApi.EntitiyDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customerorder
    {
        public int ID { get; set; }
        public string Orderno { get; set; }
        public string Type { get; set; }
        public string Typedetail { get; set; }
        public string Orderdetail { get; set; }
        public string Orderdetail1 { get; set; }
        public string Orderdetail2 { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Registerdate { get; set; }
        public string Daliverydate { get; set; }
        public string State { get; set; }
        public string Info { get; set; }
        public string Kdv { get; set; }
        public string Taxnumber { get; set; }
        public string Taxaddress { get; set; }
        public string Tc { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Town { get; set; }
        public string Email { get; set; }
        public string Salesmethod { get; set; }
        public string Salesman { get; set; }
        public string Companyname { get; set; }
        public string Companyaddress { get; set; }
        public string Usercreated { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Prepayment { get; set; }
        public string Paymentmethod { get; set; }
        public Nullable<double> Pricewaiting { get; set; }
        public string TalimatAdliye { get; set; }
        public string TalimatMahkeme { get; set; }
        public string TalimatKararno { get; set; }
        public Nullable<int> Savetype { get; set; }
    }
}
