//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarNoteWebApi.EntitiyDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_users
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Users { get; set; }
        public string Password { get; set; }
        public string Mail { get; set; }
        public string Authority { get; set; }
        public bool Isactive { get; set; }
        public string Reg_Date { get; set; }
    }
}
