//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarNoteWebApi.EntitiyDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_filemanagement
    {
        public int ID { get; set; }
        public Nullable<int> MainID { get; set; }
        public string Typename { get; set; }
        public string TypeDetail { get; set; }
        public string OrderDetail { get; set; }
        public string Fileno { get; set; }
        public string Companyname { get; set; }
        public string Costumername { get; set; }
        public string Filename { get; set; }
    }
}
